name: surf_flutter_summer_school_24
description: "Surf Flutter Summer School '24"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.0
  shared_preferences: ^2.2.3
  equatable: ^2.0.3
  dio: ^5.0.0  # подключение dio
  image_picker: ^0.8.4+3  # подключение image_picker
  http: ^0.13.4  # подключение http

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/error_image.jpg

